package os.nut.drools

import com.gpengtao.model.Message;

rule "Hello World"
  when
    m : Message( status == Message.HELLO, myMessage : message )
  then
    System.out.println("myMessage: " + myMessage);
    System.out.println("myMessage's class: "+ myMessage.getClass());
    m.setMessage( "Goodbye cruel world" );
    m.setStatus( Message.GOODBYE );
    update( m );
end

rule "GoodBye"
  when
    Message( status == Message.GOODBYE, myMessage : message )
  then
    System.out.println("myMessage: " + myMessage );
end